//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Paypackage
    {
        public int EmpPkgId { get; set; }
        public int EmpId { get; set; }
        public Nullable<decimal> EmployeeBasicSal { get; set; }
        public Nullable<decimal> EmployeeHRA { get; set; }
        public Nullable<decimal> EmployeeSpecialAllowance { get; set; }
        public Nullable<decimal> EmployeeConveyanceAllowance { get; set; }
        public Nullable<decimal> EmployeeLTA { get; set; }
        public Nullable<decimal> EmployeeMedicalAllowance { get; set; }
        public Nullable<decimal> EmployeeEducationAllowance { get; set; }
        public Nullable<decimal> EmployeeTransportAllowance { get; set; }
        public Nullable<decimal> EmployeePF { get; set; }
        public Nullable<decimal> EmployeeProfessionalTax { get; set; }
    
        public virtual Employee_Master Employee_Master { get; set; }
    }
}
