//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee_Master()
        {
            this.Leave_Transaction = new HashSet<Leave_Transaction>();
            this.EmployeeRatings = new HashSet<EmployeeRating>();
            this.Employee_Paypackage = new HashSet<Employee_Paypackage>();
            this.Employee_Paypackage_Master = new HashSet<Employee_Paypackage_Master>();
            this.EmployeeReportsToes = new HashSet<EmployeeReportsTo>();
        }
    
        public int EmpId { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> EmployeeDOB { get; set; }
        public string EmpAddress1 { get; set; }
        public string EmpAddress2 { get; set; }
        public string EmpEmail { get; set; }
        public string EmpMobile { get; set; }
        public string EmpLandline { get; set; }
        public Nullable<System.DateTime> DateofJoining { get; set; }
        public string EmpPosition { get; set; }
        public string EmpRole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave_Transaction> Leave_Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeRating> EmployeeRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Paypackage> Employee_Paypackage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Paypackage_Master> Employee_Paypackage_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeReportsTo> EmployeeReportsToes { get; set; }
    }
}
