//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Paypackage_Master
    {
        public int EmpPkgMstId { get; set; }
        public int EmpId { get; set; }
        public Nullable<decimal> EmployeeCTC { get; set; }
        public Nullable<decimal> AnnaulIncrement { get; set; }
        public Nullable<decimal> VPI { get; set; }
    
        public virtual Employee_Master Employee_Master { get; set; }
    }
}
