//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRating
    {
        public int EmployeeRatingId { get; set; }
        public int EmpId { get; set; }
        public Nullable<int> ReportsTo { get; set; }
        public int RatingId { get; set; }
    
        public virtual Employee_Master Employee_Master { get; set; }
    }
}
