//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave_Transaction
    {
        public int LeaveId { get; set; }
        public int EmpId { get; set; }
        public Nullable<decimal> LeaveAllocated { get; set; }
        public Nullable<int> LeaveApplied { get; set; }
        public Nullable<int> LeaveUsed { get; set; }
        public Nullable<decimal> Leaveforwarded { get; set; }
        public Nullable<int> CompOff { get; set; }
        public int ApprovedBy { get; set; }
    
        public virtual Employee_Master Employee_Master { get; set; }
    }
}
