//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebApiDbEntities1 : DbContext
    {
        public WebApiDbEntities1()
            : base("name=WebApiDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee_Master> Employee_Master { get; set; }
        public virtual DbSet<Employee_Paypackage> Employee_Paypackage { get; set; }
        public virtual DbSet<Employee_Paypackage_Master> Employee_Paypackage_Master { get; set; }
        public virtual DbSet<EmployeeRating> EmployeeRatings { get; set; }
        public virtual DbSet<EmployeeReportsTo> EmployeeReportsToes { get; set; }
        public virtual DbSet<Leave_Master> Leave_Master { get; set; }
        public virtual DbSet<Leave_Transaction> Leave_Transaction { get; set; }
        public virtual DbSet<RatingMaster> RatingMasters { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
